---
version: "3.3"
services:
  discord-voicebot-api:
    container_name: discord-voicebot-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "discord-voicebot-api:latest"
    restart: always
    volumes:
      - "./config:/app/config"
      - "/tmp/DiscordVoiceBot:/tmp/DiscordVoiceBot"
    ports:
      - 5080:5080
