---
version: "3.3"
services:
  discord-voicebot-api:
    container_name: discord-voicebot-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "discord-voicebot-api:latest"
    restart: "no"
    volumes:
      - "./config:/app/config"
      - "/tmp/DiscordVoiceBot:/tmp/DiscordVoiceBot"
    ports:
      - 5080:5080
    networks:
      - caching
#      - battuteapi
  discord-voicebot-client:
    container_name: discord-voicebot-client
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "discord-voicebot-client:latest"
    restart: "no"
    volumes:
      - "/tmp/DiscordVoiceBot/audio:/tmp/DiscordVoiceBot/audio"
  frittoplay-telegram-bot:
    container_name: frittoplay-telegram-bot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "frittoplay-telegram-bot:latest"
    restart: "no"
  battuteapi:
    container_name: battuteapi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "battuteapi:latest"
    volumes:
      - ./config/battuteapi_data:/usr/src/app/data
    ports:
      - 3050:3050
#    networks:
#      - battuteapi
  redis:
    image: redis
    container_name: voicebot-redis
    networks:
      - caching
networks:
  caching:
    driver: bridge
#  battuteapi:
#    name: battuteapi
