---
version: "3.3"
services:
  discord-voicebot-api:
    container_name: discord-voicebot-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "discord-voicebot-api:latest"
    restart: always
    volumes:
      - "./config:/app/config"
      - "/tmp/DiscordVoiceBot:/tmp/DiscordVoiceBot"
    ports:
      - 5080:5080  
  discord-voicebot-client:
    container_name: discord-voicebot-client
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "discord-voicebot-client:latest"
    restart: always
    volumes:
      - "/tmp/DiscordVoiceBot/audio:/tmp/DiscordVoiceBot/audio"
  trivia-game-api:
    container_name: trivia-game-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "trivia-game-api:latest"
    restart: always
    volumes:
      - "./config:/app/config"
      - "/tmp/TriviaGameApi:/tmp/TriviaGameApi"
    ports:
      - 5080:5080
