---
version: "3.3"
services:
  scemo-pezzente-api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: scemo-pezzente-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "scemo-pezzente-api:latest"
    restart: "no"
    volumes:
      - ".env:/app/.env"
      - "./config:/app/config"
      - "/tmp/scemo-pezzente-api:/tmp/scemo-pezzente-api"
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    entrypoint: ./entrypoint.sh
    #ports:
    #  - "5080:5080"
    networks:
      - caching
  battuteapi:
    build:
      context: ./battuteAPI
      dockerfile: Dockerfile
    container_name: battuteapi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "battuteapi:latest"
    volumes:
      - ./config/battuteapi_data:/usr/src/app/data
    ports:
      - 3050:3050
    restart: "no"
  scemo-pezzente-api-balancer:
    build:
      context: ./api
      dockerfile: Dockerfile.balancer
    container_name: scemo-pezzente-api-balancer
    image: "scemo-pezzente-api-balancer:latest"
    ports:
      - "5080:5080"
    depends_on:
      - scemo-pezzente-api
    volumes:
      - "/tmp/scemo-pezzente-api:/tmp/scemo-pezzente-api"
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.1.160:5080/chatbot_text/repeat/healtcheck/000000"]
      interval: 30s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    container_name: voicebot-redis
    networks:
      - caching
    restart: "no"
networks:
  caching:
    driver: bridge


